server:
    port: 8990

spring:
    #激活哪一个环境的配置文件
    profiles:
        active: dev
    jackson:
        time-zone: GMT+8
#    data:
#        redis:
#            repositories:
#                enabled: false


