#配置数据源
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/mydemo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456

      # 初始化连接大小
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      max-active: 20
      max-wait: 30000
      # 可关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat
      #可访问localhost:端口/druid/进行监控sql执行
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*" # 忽略资源



#mybatis-plus:
#    mapper-locations: classpath:mapper/*.xml
#    typeAliasesPackage: com.xiaodu.mybatisplustest.entity
#    configuration:
#      map-underscore-to-camel-case: true  #使用驼峰法映射属性
#    global-config:
#      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: 0
#      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: 2
#      #驼峰下划线转换
#      db-column-underline: true
#      #刷新mapper 调试神器
#      refresh-mapper: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      #序列接口实现类配置
#      #key-generator: com.baomidou.springboot.xxx
#      #逻辑删除配置
#      #logic-delete-value: 0
#      #logic-not-delete-value: 1
#      #自定义填充策略接口实现
#      #meta-object-handler: com.baomidou.springboot.xxx
#      #自定义SQL注入器
#      #sql-injector: com.baomidou.springboot.xxx